server:
  port: 8012
spring:
  application:
    name: sample-provider

eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
   #eureka.instance.prefer-ip-address  表示将自己的IP注册到Eureka Server上，
   #如果不配置,会将当前服务提供者所在的主机名注册到Eureka Server上。
    instance:
      prefer-ip-address: true

dubbo:
  application:
    name: sample-provider
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20880
  scan:
    basePackages: top.zhacker.ch4.api

swagger:
  basePackage: top.zhacker.sample.provider

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'

spring.sleuth.sampler.probability: 1.0